suite: Instance cap tests
release:
  name: my-release
  namespace: my-namespace
templates:
  - jcasc-config.yaml
tests:
  - it: default-cap
    asserts:
      - isKind:
          of: ConfigMap
      - hasDocuments:
          count: 1
      - documentIndex: 0
        isNotEmpty:
          path: data["jcasc-default-config.yaml"]
      - matchRegex:
          path: metadata.labels["helm.sh/chart"]
          pattern: ^jenkins-
      - documentIndex: 0
        matchSnapshot:
          path: data["jcasc-default-config.yaml"]
      - documentIndex: 0
        equal:
          path: metadata.namespace
          value: my-namespace

  - it: limited-cap
    set:
      agent.instanceCap: 5
    asserts:
      - isKind:
          of: ConfigMap
      - hasDocuments:
          count: 1
      - documentIndex: 0
        isNotEmpty:
          path: data["jcasc-default-config.yaml"]
      - matchRegex:
          path: metadata.labels["helm.sh/chart"]
          pattern: ^jenkins-
      - documentIndex: 0
        matchSnapshot:
          path: data["jcasc-default-config.yaml"]
      - documentIndex: 0
        equal:
          path: metadata.namespace
          value: my-namespace
