{{- $root := . }}
{{- if and .Values.controller.sidecars.configAutoReload.enabled (not .Values.controller.JCasC.defaultConfig) }}
{{- range $key, $val := .Values.controller.JCasC.configScripts }}
{{- if $val }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "jenkins.casc.configName" (list (printf "config-%s" $key) $ )}}
  namespace: {{ template "jenkins.namespace" $root }}
  labels:
    {{- include "jenkins.labels" $root | nindent 4 }}
    {{ template "jenkins.fullname" $root }}-jenkins-config: "true"
{{- if $root.Values.controller.JCasC.configMapAnnotations }}
  annotations:
{{ toYaml $root.Values.controller.JCasC.configMapAnnotations | indent 4 }}
{{- end }}
data:
  {{ $key }}.yaml: |-
{{ tpl $val $| indent 4 }}
{{- end }}
{{- end }}
{{- end }}
{{- if .Values.controller.JCasC.defaultConfig }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "jenkins.casc.configName" (list "jcasc-config" $ )}}
  namespace: {{ template "jenkins.namespace" $root }}
  labels:
    {{- include "jenkins.labels" $root | nindent 4 }}
    {{ template "jenkins.fullname" $root }}-jenkins-config: "true"
{{- if $root.Values.controller.JCasC.configMapAnnotations }}
  annotations:
{{ toYaml $root.Values.controller.JCasC.configMapAnnotations | indent 4 }}
{{- end }}
data:
  jcasc-default-config.yaml: |-
    {{- include "jenkins.casc.defaults" . | nindent 4 }}
{{- else }}
{{- /* When defaultConfig is false, only process configScripts - no individual security ConfigMaps */}}
{{- end }}
